import { useState, useEffect } from "react";
import Head from "next/head";
import Header from "../components/Header/Header";
import { NewsComponent } from "components/NewsComponent";
import Filter from "components/Filter";
import { makeStyles } from "@material-ui/styles";
import Grid from "@material-ui/core/Grid";
import Box from "@material-ui/core/Box";
import Link from 'next/link';
import { useRouter } from "next/router";
import { useNewsList } from "@/services/news-list";
import Button from "@material-ui/core/Button";

const useStyles = makeStyles(() => ({
  nextpage: {
    color: "black",
    marginLeft: "5px",
  },
}));

export default function Home() {
  const classes = useStyles();
  const router = useRouter();
  let page = Number(router.query.page) || 1;
  let nextPage = page + 1;
  let currentPage = page - 1;
  const [filter, setFilter] = useState("all");
  const [tags, setTags] = useState<string[]>([]);
  const { news, pagesCount } = useNewsList(tags, page);

  useEffect(() => {
    const result = filter === "all" ? [] : ["hot"];

    setTags(result);
  }, [filter]);

  return (
    <div>
      <Head>
        <title>new-news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Filter filter={filter} setFilter={setFilter} />
        <NewsComponent news={news} />
      </main>
      <footer>
         <Grid container justify="center">
          <Box m={1}>
            <h2>New-news</h2>
          </Box>
        </Grid>
        <Grid container justify="center">
          <Box m={1}>
            <Link href={"/?page=" + currentPage}>
            <Button size="small"
              variant="contained"
              color="primary"
              disabled={currentPage < 1}>
              Назад
            </Button>
            </Link>
          </Box>
          <Box m={1}>
            {Array(pagesCount)
              .fill(null)
              .map((item, index) => ( 
                <Link href={"/?page=" + (index + 1)}>
                  <a key={index} className={classes.nextpage}>
                    {index + 1}
                  </a>
                </Link>
              ))}
          </Box>
            <Box m={1}>
              <Link href={"/?page=" + nextPage}>
                <Button size="small"
                  variant="contained"
                  color="primary"
                  disabled={nextPage > pagesCount}>
                  Вперед
                </Button>
              </Link>
            </Box>
        </Grid>
      </footer>
    </div>
  );
}