import { useState, useEffect } from "react";
import Head from "next/head";
import Header from "@/components/Hearder/Header";
import { useRouter } from "next/router";
import { client } from "api/axios";
import { NewsItem } from "@/types";

export default function Home() {
  const router = useRouter();
  let id = router.query.id;
  let [item, setItem] = useState<NewsItem>();

  useEffect(() => {
    client.get(`/api/completenew?id=${id}`).then((result) => {
      setItem(result.data);
    });
  }, [id]);

  return (
    <div>
      <Head>
        <title>new-news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <img src={item?.image}/>
        <p>{item?.title}</p>
        <p>{item?.description}</p>
        <p>{item?.comments}</p>
      </main>
    </div>
  );
}
