import Head from "next/head";
import { Button } from "@material-ui/core";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>new-news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Button variant="contained" color="primary">
          Горячие
        </Button>
        <Button variant="contained" color="primary" href="#contained-buttons">
          Все
        </Button>
      </main>
    </div>
  );
}
